pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Kushal-Singwani/the_eventor.git'
            }
        }
        stage('Install & Migrate') {
            steps {
                sh '''
                    bash -c "python3 -m venv kushalenv"
                    bash -c "source kushalenv/bin/activate"
                    bash -c "pip install --upgrade pip"
                    bash -c "pip install -r requirements.txt"
                    bash -c "python3 manage.py makemigrations"
                    bash -c "python3 manage.py migrate"
                '''
            }
        }
        stage('Create Image') {
            steps {
                sh '''
                    bash -c "docker build -t the_eventor ."
                '''
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh '''
                        bash -c "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                    '''
                }
            }
        }
        stage('Tagging Image') {
            steps {
                sh '''
                    bash -c "docker tag the_eventor kushalsingwani12/the_eventor:latest"
                '''
            }
        }
        stage('Push Image') {
            steps {
                sh '''
                    bash -c "docker push kushalsingwani12/the_eventor:latest"
                '''
            }
        }
         stage('Run Server') {
            steps {
                sh '''
                    bash -c "python3 manage.py runserver 0.0.0.0:8000"
                '''
            }
        }
    }
}


